# Generated by Django 4.0.6 on 2022-07-23 05:39

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('BookStoreApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='loginpage',
            managers=[
                ('variable', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='loginpage',
            name='id',
        ),
        migrations.AlterField(
            model_name='loginpage',
            name='username',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
