# Generated by Django 4.0.6 on 2022-07-24 09:33

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('BookStoreApp', '0002_alter_loginpage_managers_remove_loginpage_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=30)),
                ('book_price', models.CharField(max_length=30)),
            ],
            managers=[
                ('variable', django.db.models.manager.Manager()),
            ],
        ),
    ]
