# Generated by Django 4.0.6 on 2022-07-24 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookStoreApp', '0004_bookdetail_delete_bookdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookDetail',
            new_name='BookDetails',
        ),
    ]
